package com.tntgroup.testdatn;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import com.tntgroup.testdatn.utils.FormatUtils;

/**
 * Auto-generated tests for FormatUtils.maskEmail
 * Generated by TestFlow
 */
public class FormatUtilsTest {

    @Test
    @DisplayName("maskEmail(test) = ***")
    void maskEmail_case1() {
        String email = "test";

        // Act
        String result = FormatUtils.maskEmail(email);

        // Assert
        assertEquals("***", result);
    }

    @Test
    @DisplayName("maskEmail(null) = ***")
    void maskEmail_withNull() {
        String email = null;

        // Act
        String result = FormatUtils.maskEmail(email);

        // Assert
        assertEquals("***", result);
    }

    @Test
    @DisplayName("maskEmail(empty) = ***")
    void maskEmail_withEmpty() {
        String email = "";

        // Act
        String result = FormatUtils.maskEmail(email);

        // Assert
        assertEquals("***", result);
    }

    @Test
    @DisplayName("maskEmail( ) = ***")
    void maskEmail_withWhitespace() {
        String email = " ";

        // Act
        String result = FormatUtils.maskEmail(email);

        // Assert
        assertEquals("***", result);
    }

    @Test
    @DisplayName("maskEmail(a) = ***")
    void maskEmail_case5() {
        String email = "a";

        // Act
        String result = FormatUtils.maskEmail(email);

        // Assert
        assertEquals("***", result);
    }

    @Test
    @DisplayName("maskEmail(\"XXXXXXXXXX...\") = ***")
    void maskEmail_case6() {
        String email = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";

        // Act
        String result = FormatUtils.maskEmail(email);

        // Assert
        assertEquals("***", result);
    }

    @Test
    @DisplayName("maskEmail(\"null_diffe...\") = ***")
    void maskEmail_case7() {
        String email = "null_different";

        // Act
        String result = FormatUtils.maskEmail(email);

        // Assert
        assertEquals("***", result);
    }

    @Test
    @DisplayName("maskEmail(no.at.sign) = ***")
    void maskEmail_case8() {
        String email = "no.at.sign";

        // Act
        String result = FormatUtils.maskEmail(email);

        // Assert
        assertEquals("***", result);
    }

    @Test
    @DisplayName("maskEmail(\"a@example....\") = a***@example.com")
    void maskEmail_case9() {
        String email = "a@example.com";

        // Act
        String result = FormatUtils.maskEmail(email);

        // Assert
        assertEquals("a***@example.com", result);
    }

    @Test
    @DisplayName("maskEmail(\"ab@example...\") = a***@example.com")
    void maskEmail_case10() {
        String email = "ab@example.com";

        // Act
        String result = FormatUtils.maskEmail(email);

        // Assert
        assertEquals("a***@example.com", result);
    }

    @Test
    @DisplayName("maskEmail(\"abc@exampl...\") = a***c@example.com")
    void maskEmail_case11() {
        String email = "abc@example.com";

        // Act
        String result = FormatUtils.maskEmail(email);

        // Assert
        assertEquals("a***c@example.com", result);
    }

}
