package com.tntgroup.testdatn;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import com.tntgroup.testdatn.utils.ValidationUtils;

/**
 * Auto-generated tests for ValidationUtils.isValidEmail
 * Generated by TestFlow
 */
public class ValidationUtilsTest {

    @Test
    @DisplayName("isValidEmail(test) = false")
    void isValidEmail_case1_returnsFalse() {
        String email = "test";

        // Act
        boolean result = ValidationUtils.isValidEmail(email);

        // Assert
        assertEquals(false, result);
    }

    @Test
    @DisplayName("isValidEmail(\"test@examp...\") = true")
    void isValidEmail_case2_returnsTrue() {
        String email = "test@example.com";

        // Act
        boolean result = ValidationUtils.isValidEmail(email);

        // Assert
        assertEquals(true, result);
    }

    @Test
    @DisplayName("isValidEmail(\"user.name@...\") = true")
    void isValidEmail_case3_returnsTrue() {
        String email = "user.name@domain.org";

        // Act
        boolean result = ValidationUtils.isValidEmail(email);

        // Assert
        assertEquals(true, result);
    }

    @Test
    @DisplayName("isValidEmail(\"contact123...\") = true")
    void isValidEmail_case4_returnsTrue() {
        String email = "contact123@company.co.uk";

        // Act
        boolean result = ValidationUtils.isValidEmail(email);

        // Assert
        assertEquals(true, result);
    }

    @Test
    @DisplayName("isValidEmail(null) = false")
    void isValidEmail_withNull_returnsFalse() {
        String email = null;

        // Act
        boolean result = ValidationUtils.isValidEmail(email);

        // Assert
        assertEquals(false, result);
    }

    @Test
    @DisplayName("isValidEmail(empty) = false")
    void isValidEmail_withEmpty_returnsFalse() {
        String email = "";

        // Act
        boolean result = ValidationUtils.isValidEmail(email);

        // Assert
        assertEquals(false, result);
    }

    @Test
    @DisplayName("isValidEmail( ) = false")
    void isValidEmail_withWhitespace_returnsFalse() {
        String email = " ";

        // Act
        boolean result = ValidationUtils.isValidEmail(email);

        // Assert
        assertEquals(false, result);
    }

    @Test
    @DisplayName("isValidEmail(a) = false")
    void isValidEmail_case8_returnsFalse() {
        String email = "a";

        // Act
        boolean result = ValidationUtils.isValidEmail(email);

        // Assert
        assertEquals(false, result);
    }

    @Test
    @DisplayName("isValidEmail(\"XXXXXXXXXX...\") = false")
    void isValidEmail_case9_returnsFalse() {
        String email = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";

        // Act
        boolean result = ValidationUtils.isValidEmail(email);

        // Assert
        assertEquals(false, result);
    }

    @Test
    @DisplayName("isValidEmail(\"null_diffe...\") = false")
    void isValidEmail_case10_returnsFalse() {
        String email = "null_different";

        // Act
        boolean result = ValidationUtils.isValidEmail(email);

        // Assert
        assertEquals(false, result);
    }

}
